---
on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: 'Go version to bootstrap'
        default: 1.18

name: Continuous Integration
jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run unit tests
      run: go test ./...
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::356933967075:role/GithubPipelineDemo
        aws-region: us-east-1
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          356933967075.dkr.ecr.us-east-1.amazonaws.com/geekshubs-demo-02:${{ github.sha }}
